### ISSUE TITLE
Social login examples

### ISSUE THREAD

**Issue by smileypop** [stelace/marketplace-demo#184]
Please add Google login and Facebook login for user creation to the demo code. Also, please include detailed instructions inside the documentation how to configure it. [Setting up social login with Stelace API](https://stelace.com/docs/users.html#sso-external-authentication)

**Comment by abruere** [comment]
Thank you for the issue, we’ll add more details in the next few days.
It’s quite similar to Github config currently mentioned in the docs (your link).

**Comment by abruere** [comment]
Additional documentation is now available, where you referred to ([High-level User docs](https://stelace.com/docs/users.html#sso-external-authentication)) and in [API reference](https://docs.api.stelace.com#15a789c6-2ee4-426c-9872-5c3b724551be) for more technical details.

I hope this helps :wink:

**Comment by smileypop** [comment]
@abruere thank you for adding this documentation.
